name: lando-memcached
services:
  defaults:
    type: memcached
  patch:
    type: memcached:1.5.11

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/memcached": ./../../